Imported Data for Ben and Jerry's from Drive

In [0]:
#=======INPUT: LOCATION LAT/LONG=======#
Location = (-22.8145,-43.2457)  

#=======INPUT: PATH TO DATAFRAME FILE=======#
pandas_file = '/gdrive/Shared drives/INF560/Code/Data Files/Dataframes/data11-BenJerry.csv'

#=======OUTPUT FILE PATH=======#
output_file = '/gdrive/Shared drives/INF560/Code/Code Files/pickles/loc11model.pkl'

import pandas as pd
df=pd.read_excel(pandas_file)

In [0]:
df.head(5)

Unnamed: 0    0        1                  2                            3
0           0  4.1  Level 3  00:16:98:70:ba:33  2019-12-14 21:10:08.164 UTC
1           1  4.1  Level 3  28:16:7f:e0:45:f4  2019-12-27 18:51:20.347 UTC
2           2  4.1  Level 3  2c:59:8a:67:d7:d6  2019-12-07 22:13:11.822 UTC
3           3  4.1  Level 3  fc:64:3a:c7:8d:fe  2019-12-25 00:56:24.117 UTC
4           4  4.1  Level 3  38:71:de:bd:35:3f  2019-12-22 08:54:53.432 UTC

In [0]:
df = df.drop('Unnamed: 0', 1)

In [0]:
df

0        1                  2                            3
0    4.1  Level 3  00:16:98:70:ba:33  2019-12-14 21:10:08.164 UTC
1    4.1  Level 3  28:16:7f:e0:45:f4  2019-12-27 18:51:20.347 UTC
2    4.1  Level 3  2c:59:8a:67:d7:d6  2019-12-07 22:13:11.822 UTC
3    4.1  Level 3  fc:64:3a:c7:8d:fe  2019-12-25 00:56:24.117 UTC
4    4.1  Level 3  38:71:de:bd:35:3f  2019-12-22 08:54:53.432 UTC
..   ...      ...                ...                          ...
327  4.1  Level 3  6c:e8:5c:e5:ed:fd  2019-12-21 17:29:36.497 UTC
328  4.1  Level 3  dc:bf:e9:eb:21:95  2019-12-17 07:12:37.901 UTC
329  4.1  Level 3  44:91:60:46:4e:ab  2019-12-11 20:27:45.565 UTC
330  4.1  Level 3  7c:a1:ae:03:79:8c  2019-12-21 11:20:37.832 UTC
331  4.1  Level 3  e8:e8:b7:71:2c:42  2019-12-11 21:05:51.607 UTC

[332 rows x 4 columns]

In [0]:
df.columns = ['Ratings', 'level','MAC-ID','Timestamp']

In [0]:
df

Ratings    level             MAC-ID                    Timestamp
0        4.1  Level 3  00:16:98:70:ba:33  2019-12-14 21:10:08.164 UTC
1        4.1  Level 3  28:16:7f:e0:45:f4  2019-12-27 18:51:20.347 UTC
2        4.1  Level 3  2c:59:8a:67:d7:d6  2019-12-07 22:13:11.822 UTC
3        4.1  Level 3  fc:64:3a:c7:8d:fe  2019-12-25 00:56:24.117 UTC
4        4.1  Level 3  38:71:de:bd:35:3f  2019-12-22 08:54:53.432 UTC
..       ...      ...                ...                          ...
327      4.1  Level 3  6c:e8:5c:e5:ed:fd  2019-12-21 17:29:36.497 UTC
328      4.1  Level 3  dc:bf:e9:eb:21:95  2019-12-17 07:12:37.901 UTC
329      4.1  Level 3  44:91:60:46:4e:ab  2019-12-11 20:27:45.565 UTC
330      4.1  Level 3  7c:a1:ae:03:79:8c  2019-12-21 11:20:37.832 UTC
331      4.1  Level 3  e8:e8:b7:71:2c:42  2019-12-11 21:05:51.607 UTC

[332 rows x 4 columns]

Formatted the Timestamps into dateTime types from string 

In [0]:
df['Timestamp'] = df['Timestamp'].str.replace(r'UTC', '')

In [0]:
df.head(5)

Ratings    level             MAC-ID                 Timestamp
0      4.1  Level 3  00:16:98:70:ba:33  2019-12-14 21:10:08.164 
1      4.1  Level 3  28:16:7f:e0:45:f4  2019-12-27 18:51:20.347 
2      4.1  Level 3  2c:59:8a:67:d7:d6  2019-12-07 22:13:11.822 
3      4.1  Level 3  fc:64:3a:c7:8d:fe  2019-12-25 00:56:24.117 
4      4.1  Level 3  38:71:de:bd:35:3f  2019-12-22 08:54:53.432

In [0]:
df['Timestamp']=pd.to_datetime(df['Timestamp'])

In [0]:
df1=df

In [0]:
df1.head(5)

Ratings    level             MAC-ID               Timestamp
0      4.1  Level 3  00:16:98:70:ba:33 2019-12-14 21:10:08.164
1      4.1  Level 3  28:16:7f:e0:45:f4 2019-12-27 18:51:20.347
2      4.1  Level 3  2c:59:8a:67:d7:d6 2019-12-07 22:13:11.822
3      4.1  Level 3  fc:64:3a:c7:8d:fe 2019-12-25 00:56:24.117
4      4.1  Level 3  38:71:de:bd:35:3f 2019-12-22 08:54:53.432

Grouped the data by the MAC ID and sorted by Timestamp . This was done to extract consecutive wait times between 2 timestamps which is indicative of the time duration for which a user has been around this location .

In [0]:
df1=df1.sort_values('Timestamp', ascending=True)

In [0]:
df1.head(5)

Ratings    level             MAC-ID               Timestamp
270      4.1  Level 3  0c:cb:85:c3:7e:83 2019-12-01 00:28:43.372
201      4.1  Level 3  30:07:4d:96:ea:21 2019-12-01 06:57:33.354
129      4.1  Level 3  5c:1d:d9:b0:07:2a 2019-12-01 09:52:55.137
15       4.1  Level 3  58:d9:c3:cf:4f:2b 2019-12-01 10:23:53.427
155      4.1  Level 3  b4:c4:fc:4f:a3:c7 2019-12-01 16:02:10.269

Computed the wait-time in seconds 

In [0]:
df1['Wait-Time']=df1['Timestamp'].diff().astype('timedelta64[s]')

In [0]:
df1['Wait-Time'].fillna((df1['Wait-Time'].mean()), inplace=True)

In [0]:
df1.head(50)

Ratings    level             MAC-ID               Timestamp     Wait-Time
270      4.1  Level 3  0c:cb:85:c3:7e:83 2019-12-01 00:28:43.372   7782.691843
201      4.1  Level 3  30:07:4d:96:ea:21 2019-12-01 06:57:33.354  23329.000000
129      4.1  Level 3  5c:1d:d9:b0:07:2a 2019-12-01 09:52:55.137  10521.000000
15       4.1  Level 3  58:d9:c3:cf:4f:2b 2019-12-01 10:23:53.427   1858.000000
155      4.1  Level 3  b4:c4:fc:4f:a3:c7 2019-12-01 16:02:10.269  20296.000000
276      4.1  Level 3  b4:f0:ab:d5:66:22 2019-12-02 18:39:07.679  95817.000000
177      4.1  Level 3  04:d6:aa:8d:ce:52 2019-12-02 20:05:42.128   5194.000000
117      4.1  Level 3  88:29:9c:c1:21:1b 2019-12-02 20:25:17.632   1175.000000
119      4.1  Level 3  88:29:9c:c1:21:1b 2019-12-02 20:25:17.633      0.000000
72       4.1  Level 3  58:20:59:72:30:91 2019-12-02 23:54:14.245  12536.000000
37       4.1  Level 3  d4:dc:cd:91:2d:b3 2019-12-03 11:27:22.407  41588.000000
36       4.1  Level 3  d4:dc:cd:91:2d:b3 2019-12-03 11:27:22.411      0.000000
138      4.1  Level 3  98:b8:e3:ad:7a:91 2019-12-03 13:41:10.985   8028.000000
264      4.1  Level 3  64:a2:f9:30:bd:e4 2019-12-03 19:04:02.036  19371.000000
312      4.1  Level 3  50:a6:7f:4a:d7:15 2019-12-03 19:12:52.509    530.000000
76       4.1  Level 3  8c:45:00:2a:9f:37 2019-12-03 20:24:31.452   4298.000000
186      4.1  Level 3  a0:c9:a0:f9:58:cf 2019-12-03 21:31:46.418   4034.000000
229      4.1  Level 3  2c:ae:2b:13:b7:1f 2019-12-03 21:54:35.117   1368.000000
315      4.1  Level 3  c8:3d:dc:87:ce:8a 2019-12-03 22:39:53.970   2718.000000
204      4.1  Level 3  04:d4:c4:a1:0e:14 2019-12-04 05:41:53.206  25319.000000
64       4.1  Level 3  7c:8b:b5:bc:22:73 2019-12-04 11:49:24.519  22051.000000
240      4.1  Level 3  fc:ee:e6:0e:42:e8 2019-12-04 14:38:12.224  10127.000000
135      4.1  Level 3  dc:bf:e9:3b:cd:f3 2019-12-04 15:02:41.185   1468.000000
325      4.1  Level 3  bc:41:01:7a:8e:45 2019-12-04 17:04:25.371   7304.000000
326      4.1  Level 3  bc:41:01:7a:8e:45 2019-12-04 17:04:27.338      1.000000
200      4.1  Level 3  74:b5:87:40:e5:ce 2019-12-05 00:06:13.443  25306.000000
58       4.1  Level 3  dc:bf:e9:0b:0b:8c 2019-12-05 00:08:12.149    118.000000
163      4.1  Level 3  50:92:b9:8c:44:22 2019-12-05 10:44:47.656  38195.000000
18       4.1  Level 3  dc:bf:e9:cc:0c:69 2019-12-05 12:13:30.503   5322.000000
292      4.1  Level 3  38:9a:f6:7c:92:93 2019-12-05 12:17:26.642    236.000000
192      4.1  Level 3  bc:98:df:ef:d5:80 2019-12-05 14:30:38.428   7991.000000
83       4.1  Level 3  30:cb:f8:66:22:23 2019-12-05 15:18:43.947   2885.000000
205      4.1  Level 3  d0:04:01:8f:e2:99 2019-12-05 18:43:23.450  12279.000000
273      4.1  Level 3  44:91:60:6c:53:36 2019-12-05 22:15:33.320  12729.000000
239      4.1  Level 3  70:fd:46:0e:cc:1c 2019-12-05 22:16:21.269     47.000000
67       4.1  Level 3  60:83:73:07:e0:30 2019-12-05 23:50:06.413   5625.000000
114      4.1  Level 3  0c:cb:85:92:13:fa 2019-12-06 06:36:25.470  24379.000000
225      4.1  Level 3  00:9d:6b:e2:f5:2d 2019-12-06 11:14:09.646  16664.000000
306      4.1  Level 3  38:9a:f6:fa:4d:b1 2019-12-06 11:28:13.794    844.000000
305      4.1  Level 3  38:9a:f6:fa:4d:b1 2019-12-06 11:28:13.811      0.000000
193      4.1  Level 3  20:32:6c:20:f7:9d 2019-12-06 14:08:55.199   9641.000000
199      4.1  Level 3  44:91:60:7b:46:5d 2019-12-06 15:22:03.367   4388.000000
10       4.1  Level 3  64:c7:53:48:95:ea 2019-12-06 15:50:44.635   1721.000000
8        4.1  Level 3  64:c7:53:48:95:ea 2019-12-06 15:53:58.158    193.000000
265      4.1  Level 3  a8:db:03:6a:f4:ad 2019-12-06 19:31:15.331  13037.000000
168      4.1  Level 3  6c:c7:ec:a7:32:b3 2019-12-06 20:20:38.798   2963.000000
167      4.1  Level 3  6c:c7:ec:a7:32:b3 2019-12-06 20:20:38.855      0.000000
222      4.1  Level 3  64:b0:a6:dd:9e:65 2019-12-06 22:10:14.108   6575.000000
20       4.1  Level 3  34:c0:59:64:5f:bf 2019-12-07 08:05:28.180  35714.000000
210      4.1  Level 3  5c:03:39:06:e5:7c 2019-12-07 09:

Extracted the location of various gates by the flights that depart from them in terminal two ( Google Maps & Aeroporto de galeo website data ) and computed the GeoPy distance between the current outlet and the Gates .

In [0]:
Gate_Delta = (-22.8151,-43.2457)

In [0]:
Gate_United= (-22.8151,-43.2455)

In [0]:
Gate_AA= (-22.8148,-43.2449)

In [0]:
Gate_Emirates= (-22.8141,-43.2453)

In [0]:
Gate_Lufthansa= (-22.8142,-43.2457)

In [0]:
Gate_Copa = (-22.8140,-43.2455)

In [0]:
Gate_AirFrance = (-22.8141,-43.2460)

In [0]:
Gate_AirArg = (-22.8142,-43.2454)

In [0]:
Gate_Airitalia = (-22.8142,-43.2460)

In [0]:
from geopy.distance import vincenty

In [0]:
df1['dist_DA'] = vincenty(Location,Gate_Delta).meters

In [0]:
df1['dist_UA'] =vincenty(Location,Gate_United).meters

In [0]:
df1['dist_AA'] =vincenty(Location,Gate_AA).meters

In [0]:
df1['dist_EM']= vincenty(Location,Gate_Emirates).meters

In [0]:
df1['dist_LF']= vincenty(Location,Gate_Lufthansa).meters

In [0]:
df1['dist_Copa'] = vincenty(Location,Gate_Copa).meters

In [0]:
df1['dist_AF']  = vincenty(Location,Gate_AirFrance).meters

In [0]:
df1['dist_AG'] = vincenty(Location,Gate_AirArg).meters

In [0]:
df1['dist_AI'] = vincenty(Location,Gate_Airitalia).meters

Appended the geodistances in meters as additional columns in the dataframe

In [0]:
df1.head(5)

Ratings    level             MAC-ID  ...    dist_AF    dist_AG    dist_AI
270      4.1  Level 3  0c:cb:85:c3:7e:83  ...  53.951313  45.302176  45.302176
201      4.1  Level 3  30:07:4d:96:ea:21  ...  53.951313  45.302176  45.302176
129      4.1  Level 3  5c:1d:d9:b0:07:2a  ...  53.951313  45.302176  45.302176
15       4.1  Level 3  58:d9:c3:cf:4f:2b  ...  53.951313  45.302176  45.302176
155      4.1  Level 3  b4:c4:fc:4f:a3:c7  ...  53.951313  45.302176  45.302176

[5 rows x 14 columns]

Performed Binning of the data into target risk levels based on stats from the following link:

[AirlineFlightDelays Stats : A Survey](https://stat-or.unc.edu/files/2018/09/Paper3_MSOM_2012_AirlineFlightDelays.pdf)


Target Variable recommended risk levels -
**Encoding Scheme :**

*   Low Risk - 0
*   Medium Risk - 1


*   High Risk -2





In [0]:
median=df1['Wait-Time'].median()

In [0]:
percentile_75 = df1['Wait-Time'].quantile(q=0.75)

In [0]:
percentile_25 = df1['Wait-Time'].quantile(q=0.25)

In [0]:
df1.shape

(332, 14)

In [0]:
df1['Risk-level'] = 0

In [0]:
df1.loc[ (df1['Wait-Time'] > median) & (df1.Ratings >= 3.0 ),'Risk-level'] = 2

In [0]:
df1.loc[ (df1['Wait-Time'] <= median) & (df1['Wait-Time'] > percentile_25)  & (df1.Ratings >= 3.0 ),'Risk-level'] = 1

In [0]:
df1.loc[(df1['Wait-Time'] <= percentile_25 ) & (df1.Ratings >= 3.0 ),'Risk-level'] = 0

In [0]:
len(df1[df1['Risk-level']==2])

166

In [0]:
df1.shape

(332, 15)

In [0]:
df1= df1.drop('Timestamp', 1)


In [0]:
df1= df1.drop('MAC-ID', 1)
df1= df1.drop('level',1)

In [0]:
df1.shape

(332, 12)

In [0]:
import seaborn as sns
sns.set(style="whitegrid")
tips = df1
ax = sns.boxplot(x=df1['Risk-level'],y=df1['Wait-Time'])
ax.set_ylim([0, 100])

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


(0.0, 100.0)

Data has now been completely preprocessed and ready for analysis 

Train-test Split Performed : ( 80:20 split taken . 80% for training the model and 20% for testing the model ) . Will use the training set itself to perform 10 fold cross validation for model selection

In [0]:
data_x= df1.iloc[:,0:11]
data_y =df1.iloc[:,11:12]

In [0]:
import math
trainVal = math.trunc(df1.shape[0]*.8)
numRows = df1.shape[0]

In [0]:
train_x = data_x.iloc[0:trainVal,:]
train_y = data_y.iloc[0:trainVal,:]
test_x = data_x.iloc[trainVal:numRows,:]
test_y = data_y.iloc[trainVal:numRows,:]

In [0]:
from sklearn.utils import shuffle
train_x,train_y = shuffle(train_x,train_y)

In [0]:
test_x,test_y = shuffle(test_x,test_y)

In [0]:
test_x.shape

(67, 11)

# Logistic Regression Model

In [0]:
from sklearn.linear_model import LogisticRegressionCV 
from sklearn.metrics import roc_curve, auc, confusion_matrix
from sklearn.metrics import roc_auc_score
from sklearn.multiclass import OneVsRestClassifier

In [0]:
mdl = LogisticRegressionCV(cv=10)

In [0]:
mdl.fit(train_x,train_y)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iteratio

LogisticRegressionCV(Cs=10, class_weight=None, cv=10, dual=False,
                     fit_intercept=True, intercept_scaling=1.0, l1_ratios=None,
                     max_iter=100, multi_class='auto', n_jobs=None,
                     penalty='l2', random_state=None, refit=True, scoring=None,
                     solver='lbfgs', tol=0.0001, verbose=0)

In [0]:
preds_y=mdl.predict(test_x)

In [0]:
training_acc = mdl.score(train_x,train_y)
test_acc = mdl.score(test_x,test_y)

Evaluation Metrics : Accuracy , Precision , Recall , F-1 score and Area under the curve - Reason for selection of these metrics ( Classification problem statement )

In [0]:
test_acc 

1.0

In [0]:
from sklearn import metrics
from sklearn.metrics import classification_report

confusion_mat = metrics.confusion_matrix(test_y,preds_y)
report_Logistic=classification_report(test_y,preds_y)

In [0]:
print(confusion_mat)

[[11  0  0]
 [ 0 16  0]
 [ 0  0 40]]


In [0]:
print(report_Logistic)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        40

    accuracy                           1.00        67
   macro avg       1.00      1.00      1.00        67
weighted avg       1.00      1.00      1.00        67



In [0]:
classes = [0,1,2]
import numpy as np
import matplotlib.pyplot as plt

In [0]:
from itertools import cycle
from scipy import interp
from sklearn.preprocessing import label_binarize
def report_multi_class(train_X_norm, train_Y, test_Y, y_predict, y_score):
    lw = 2
    con_matrix = confusion_matrix(test_Y, y_predict)    
    train_Y = label_binarize(train_Y, classes=classes)
    test_Y = label_binarize(test_Y, classes=classes)
    y_predict = label_binarize(y_predict, classes=classes)
    n_classes = train_Y.shape[1]
    fpr = dict()
    tpr = dict()
    roc_auc = dict()
    for i in range(n_classes):
        fpr[i], tpr[i], _ = roc_curve(test_Y[:, i], y_score[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])
    fpr["micro"], tpr["micro"], _ = roc_curve(test_Y.ravel(), y_score.ravel())
    roc_auc["micro"] = auc(fpr["micro"], tpr["micro"])
    # Compute macro-average ROC curve and ROC area

# First aggregate all false positive rates
    all_fpr = np.unique(np.concatenate([fpr[i] for i in range(n_classes)]))

    # Then interpolate all ROC curves at this points
    mean_tpr = np.zeros_like(all_fpr)
    for i in range(n_classes):
        mean_tpr += interp(all_fpr, fpr[i], tpr[i])

    # Finally average it and compute AUC
    mean_tpr /= n_classes

    fpr["macro"] = all_fpr
    tpr["macro"] = mean_tpr
    roc_auc["macro"] = auc(fpr["macro"], tpr["macro"])

    plt.figure()
    colors = cycle(['aqua', 'darkorange', 'cornflowerblue', 'pink', 'olive', 
                    'brown', 'wheat'])
    for i, color in zip(range(n_classes), colors):
        plt.plot(fpr[i], tpr[i], color=color, lw=lw,
                 label='ROC curve of class {0} (area = {1:0.2f})'
                 ''.format(classes[i], roc_auc[i]))
    
    plt.plot([0, 1], [0, 1], 'k--', lw=lw)
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title('Some extension of Receiver operating characteristic to multi-class')
    plt.legend(loc="upper left")
    plt.show()
    
    print("Confusion Matrix: \n", con_matrix)

In [0]:
y_score = mdl.decision_function(test_x)
report_multi_class(train_x, train_y, test_y, preds_y, y_score)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: DeprecationWarning: scipy.interp is deprecated and will be removed in SciPy 2.0.0, use numpy.interp instead


Confusion Matrix: 
 [[11  0  0]
 [ 0 16  0]
 [ 0  0 40]]


# RBF Kernelized Support vector machine 

In [0]:
from sklearn.svm import SVC
from sklearn import svm

mdl_svm=svm.SVC(kernel='rbf')
mdl_svm.fit(train_x,train_y)
preds_svm=mdl_svm.predict(test_x)

/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [0]:
test_acc_svm = mdl_svm.score(test_x,test_y)

Evaluation Metrics : Accuracy , precision , recall , F1-score and Area under the curve

In [0]:
test_acc_svm

0.9552238805970149

In [0]:
from sklearn import metrics
from sklearn.metrics import classification_report

confusion_mat_svm = metrics.confusion_matrix(test_y,preds_svm)
report_svm=classification_report(test_y,preds_svm)

In [0]:
print(confusion_mat_svm)
print(report_svm)

[[11  0  0]
 [ 3 13  0]
 [ 0  0 40]]
              precision    recall  f1-score   support

           0       0.79      1.00      0.88        11
           1       1.00      0.81      0.90        16
           2       1.00      1.00      1.00        40

    accuracy                           0.96        67
   macro avg       0.93      0.94      0.93        67
weighted avg       0.96      0.96      0.96        67



In [0]:
y_score_svm = mdl_svm.decision_function(test_x)
report_multi_class(train_x, train_y, test_y, preds_svm, y_score_svm)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:27: DeprecationWarning: scipy.interp is deprecated and will be removed in SciPy 2.0.0, use numpy.interp instead


Confusion Matrix: 
 [[11  0  0]
 [ 3 13  0]
 [ 0  0 40]]


# Multinomial Naive Bayes Classifier reinforced by one vs all classifier

In [0]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.multiclass import OneVsRestClassifier

In [0]:
mdl2= OneVsRestClassifier(MultinomialNB())

In [0]:
mdl2.fit(train_x,train_y)

OneVsRestClassifier(estimator=MultinomialNB(alpha=1.0, class_prior=None,
                                            fit_prior=True),
                    n_jobs=None)

In [0]:
pred_y_NB=mdl2.predict(test_x)

In [0]:
training_acc_NB = mdl2.score(train_x,train_y)
test_acc_NB = mdl2.score(test_x,test_y)

Evaluation Metrics : Accuracy , precision , recall , F1-score 

In [0]:
test_acc_NB

0.746268656716418

In [0]:
from sklearn import metrics
from sklearn.metrics import classification_report

confusion_mat_NB = metrics.confusion_matrix(test_y,pred_y_NB)
report_NB=classification_report(test_y,pred_y_NB)

/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [0]:
print(confusion_mat_NB)

[[ 0 11  0]
 [ 0 10  6]
 [ 0  0 40]]


In [0]:
print(report_NB)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00        11
           1       0.48      0.62      0.54        16
           2       0.87      1.00      0.93        40

    accuracy                           0.75        67
   macro avg       0.45      0.54      0.49        67
weighted avg       0.63      0.75      0.68        67



# K Nearest Neighbors Classifier 

In [0]:
from sklearn.neighbors import KNeighborsClassifier

In [0]:
mdl3=KNeighborsClassifier(n_neighbors=5)

In [0]:
mdl3.fit(train_x,train_y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  """Entry point for launching an IPython kernel.


KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [0]:
preds_KNN=mdl3.predict(test_x)

In [0]:
training_acc_KNN = mdl3.score(train_x,train_y)
test_acc_KNN = mdl3.score(test_x,test_y)

Evaluation Metrics : Accuracy ,Precision ,recall and F1-score 

In [0]:
test_acc_KNN

0.9701492537313433

In [0]:
from sklearn import metrics

confusion_mat_KNN = metrics.confusion_matrix(test_y,preds_KNN)
report_KNN=classification_report(test_y,preds_KNN)

In [0]:
print(confusion_mat_KNN)
print(report_KNN)

[[11  0  0]
 [ 0 14  2]
 [ 0  0 40]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      0.88      0.93        16
           2       0.95      1.00      0.98        40

    accuracy                           0.97        67
   macro avg       0.98      0.96      0.97        67
weighted avg       0.97      0.97      0.97        67



# Random forest classifier ( Boosted decision trees )

In [0]:
from sklearn.ensemble import RandomForestClassifier

mdl_RF = RandomForestClassifier(n_estimators=10,oob_score =True,class_weight='balanced',max_depth=20)
mdl_RF.fit(train_x, train_y)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py:523: UserWarning: Some inputs do not have OOB scores. This probably means too few trees were used to compute any reliable oob estimates.
  warn("Some inputs do not have OOB scores. "
/usr/local/lib/python3.6/dist-packages/sklearn/ensemble/_forest.py:528: RuntimeWarning: invalid value encountered in true_divide
  predictions[k].sum(axis=1)[:, np.newaxis])


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight='balanced',
                       criterion='gini', max_depth=20, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
preds_RF=mdl_RF.predict(test_x)


Evaluation Metrics : Out of Bag error estimate , Confusion Matrix 

In [0]:
confusion_mat = confusion_matrix(test_y,preds_RF)
report_RF=classification_report(test_y,preds_RF)
oob_score = mdl_RF.oob_score_
oob_error = 1 - oob_score

print("OOB score: ",oob_score)
print("Out of bag error estimate test data: ",oob_error)
print("Confusion Matrix test data:\n",confusion_mat)

OOB score:  0.9735849056603774
Out of bag error estimate test data:  0.026415094339622636
Confusion Matrix test data:
 [[11  0  0]
 [ 0 15  1]
 [ 0  0 40]]


After comparing the evaluation metrics of the above built classifiers and the efficiency and complexity of the model in runtime considering that we would be compressing the model as a pickle file to deploy it in the back end of a web application , RBF SVM seem ideal for this scenario 

In [0]:
import pickle

In [0]:
pickle.dump(mdl_svm, open(output_file,'wb'))

In [0]:
pickle_loader = pickle.load(open(output_file,'rb'))

In [0]:
preds_production=pickle_loader.predict(test_x)

In [0]:
pickle_loader.score(test_x,test_y)

0.9552238805970149

In [0]:
test_x.head()

Ratings  Wait-Time    dist_DA  ...    dist_AF    dist_AG    dist_AI
295      4.1        0.0  66.444857  ...  53.951313  45.302176  45.302176
102      4.1    17237.0  66.444857  ...  53.951313  45.302176  45.302176
75       4.1     3739.0  66.444857  ...  53.951313  45.302176  45.302176
197      4.1    17966.0  66.444857  ...  53.951313  45.302176  45.302176
78       4.1     9426.0  66.444857  ...  53.951313  45.302176  45.302176

[5 rows x 11 columns]